# Generated by Django 5.0.6 on 2024-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorbase_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(default='Max', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default='Mustermann', max_length=100),
        ),
    ]
