# Generated by Django 5.0.6 on 2024-05-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorbase_backend', '0003_remove_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='descritpion',
            new_name='description',
        ),
    ]
